### ISSUE TITLE
Not getting default WebView scrolling behavior

### ISSUE THREAD

**Issue by khalid-hussain** [naoak/WebViewMarker#5]
Hi there,

I am trying out the sample and have read the other issues and understand their implications. What I would like to know is how can I restore the default WebView scrolling behavior while using this library?

**Comment by gregko** [comment]
See my comment on StackOverflow: https://github.com/naoak/WebViewMarker - seems to fix the scrolling issue.

**Comment by naoak** [comment]
#6 PR fixed this issue.
